// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $GoToTopButton from "./islands/GoToTopButton.tsx";
import * as $Home from "./islands/Home.tsx";
import * as $ImagesCompressor from "./islands/ImagesCompressor.tsx";
import * as $ImagesGallery from "./islands/ImagesGallery.tsx";
import * as $ImagesInput from "./islands/ImagesInput.tsx";
import * as $home_CompressingPage from "./islands/home/CompressingPage.tsx";
import * as $home_SetupPage from "./islands/home/SetupPage.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/GoToTopButton.tsx": $GoToTopButton,
    "./islands/Home.tsx": $Home,
    "./islands/ImagesCompressor.tsx": $ImagesCompressor,
    "./islands/ImagesGallery.tsx": $ImagesGallery,
    "./islands/ImagesInput.tsx": $ImagesInput,
    "./islands/home/CompressingPage.tsx": $home_CompressingPage,
    "./islands/home/SetupPage.tsx": $home_SetupPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
